name: dagger
on:
  push:
    branches: [techlab]

jobs:
  scan:
    name: vulnerability-scan
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: scan
        uses: dagger/dagger-for-github@v6
        with:
          version: "latest"
          verb: call
          module: .
          args: vulnerability-scan --context=. export --path=.
      - name: commit and push
        run: git add scans && git commit -m "Update Scan results" && git push
